-- 1
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E 
LEFT JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SUBSTR(EMP_NO,1,1) = '7'
AND SUBSTR(EMP_NO,8,1) = '2'
AND SUBSTR(EMP_NAME,1,1) = '전';
-- 2 
SELECT * FROM
(SELECT EMP_ID, EMP_NAME, 
    EXTRACT(YEAR FROM SYSDATE) -
    (DECODE(SUBSTR(EMP_NO,8,1) ,'1',19,'2',19, 20) || SUBSTR(EMP_NO,1,2)) 나이
, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E 
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID 
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
ORDER BY 3)
WHERE ROWNUM = 1;
--3
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE EMP_NAME LIKE '%형%';
--4 
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE E 
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
JOIN JOB USING(JOB_CODE)
WHERE DEPT_CODE IN ('D5','D6');
--5
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
LEFT JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
WHERE BONUS IS NOT NULL;
--6
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E 
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID 
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE;
--7
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID 
LEFT JOIN LOCATION L ON LOCATION_ID = LOCAL_CODE
LEFT JOIN NATION USING(NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국','일본');
-- 8
SELECT E1.EMP_NAME, E1.DEPT_CODE, E2.EMP_NAME
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON (E1.DEPT_CODE = E2.DEPT_CODE AND E1.EMP_ID != E2.EMP_ID)
ORDER BY 1;
-- 9
SELECT EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE 
JOIN JOB USING(JOB_CODE)
WHERE JOB_CODE IN ('J4','J7') 
AND NVL(BONUS, 0) = 0; 
--10
SELECT EMP_iD, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE , ROWNUM 
FROM (
    SELECT EMP_iD, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE 
    FROM EMPLOYEE 
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID 
    JOIN JOB USING(JOB_CODE)
    ORDER BY (SALARY + SALARY * NVL(BONUS,0)) * 12 DESC)
WHERE ROWNUM <= 5;
-- 11
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON DEPT_CODE= DEPT_ID
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) > (
    SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE);
-- 11-2
SELECT * 
FROM (
    SELECT DEPT_TITLE, SUM(SALARY) AS 급여합
    FROM EMPLOYEE 
    LEFT JOIN DEPARTMENT ON DEPT_CODE= DEPT_ID
    GROUP BY DEPT_TITLE)
WHERE 급여합 > (SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE);
-- 3
WITH EMP_SALARY AS (
    SELECT DEPT_TITLE, SUM(SALARY) AS 급여합
    FROM EMPLOYEE 
    LEFT JOIN DEPARTMENT ON DEPT_CODE= DEPT_ID
    GROUP BY DEPT_TITLE
)
SELECT * 
FROM EMP_SALARY
WHERE 급여합 > (SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE);
-- 13
WITH EMP_SUMMARY AS (
    SELECT SUM(SALARY)
    FROM EMPLOYEE
    UNION 
    SELECT AVG(SALARY)
    FROM EMPLOYEE
)
SELECT * FROM EMP_SUMMARY;






