--1
INSERT INTO TB_CLASS_TYPE
VALUES ('01','전공필수');
INSERT INTO TB_CLASS_TYPE
VALUES ('05','논문지도');

--2
CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
    FROM tb_student;

--3 -- 나중에 확인하기
--CREATE TABLE TB_국어국문학과
--AS SELECT STUDENT_NO 학번, STUDETN_NAME 학생이름, 19 || SUBSTR(STUDENT_SSN) STUDENT_SSN
--PROFESSOR_NAME 교수이름
--FROM TB_STUDENT S
--LEFT JOIN TB_PROFESSOR P ON COACH_PROFESSOR_NO = PROFESSOR_NO
--WHERE S.DEPARTMENT_NO
--=()


--4
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

--5
UPDATE TB_STUDENT
SET STUDETN_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--6
UPDATE TB_STUDENT
SET STUDETN_SSN = SUBSTR(STUDETN_SSN, 1, 6);

--7
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501' AND
CLASS_NO = (SELECT CLASS_NO FROM TB_CLASS WHERE CLASS_NAME = '피부생리학')
AND student_no = (SELECT SUDENT_NO FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE student_name = '김명훈' AND DEPARTMENT_NAME ='의학과');

--8
DELETE FROM TB_GRADE G
WHERE EXISTS(
    SELECT 1
    FROM TB_STUDENT S
    WHERE G.STUDETN_NO = s.student_no
    AND s.absence_yn = 'Y'
);

-- 못한건 선생님 자료에서



