-- ADDITIONAL SELECT
-- 1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY 1;

-- 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

-- 3
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) = '9'
AND (STUDENT_ADDRESS LIKE '강원%'
OR STUDENT_ADDRESS LIKE '경기도%')
ORDER BY 1;
--
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE   (STUDENT_ADDRESS LIKE '강원%'
        OR STUDENT_ADDRESS LIKE '경기도%')
        AND SUBSTR(STUDENT_NO, 1, 1) != 'A'
ORDER BY 1;

-- 4 (이거 LEFT 조인 한번 잘활용해서 해보기 )
SELECT *
FROM TB_PROFESSOR;
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR TP
JOIN tb_class_professor TCP ON (TP.PROFESSOR_NO = tcp.professor_no)
JOIN tb_class TC ON (TP.CLESS_no = tcp.CLESS_no)
JOIN tb_department TD ON (TD.DEPARTMENT_NO = TC.DEPARTMENT_NO)
WHERE tD.department_NAME = '법학과';
--
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM
tb_department WHERE tD.department_NAME = '법학과');

-- 5
-- 나중에 풀어봐라
--
-- 선생님 풀이는  나중애 저기서 보기

-- 6

--
SELECT * 
FROM TB_STUDENT
JOIN tb_department USING(department_no)
ORDER BY SUBSTR(STUDENT_NAME,2);

-- 7

--
SELECT * 
FROM tb_class
JOIN tb_department USING(department_no);

-- 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM tb_class TC
JOIN tb_department TD ON (TD.CLESS_no = tc.CLESS_no)
JOIN tb_professor TP ON ts.coach_professor_no = tp.professor_no;
--
SELECT CLASS_NAME, professor_name
FROM tb_class
JOIN tb_class_professor USING(CLASS_NO)
JOIN tb_professor USING(professor_no);

-- 9

--
SELECT CLASS_NAME, professor_name
FROM tb_class C
JOIN tb_class_professor USING(CLASS_NO)
JOIN tb_professor USING(professor_no)
JOIN tb_department D ON c.department_no = d.department_no -- USING 못사용하는 이유 위에서 같은게 3개나 있어서
WHERE CATEGORY = '인문사회';

-- 10

--
SELECT student_no "학번", student_name "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM tb_student
JOIN tb_grade USING (student_no)
WHERE department_no = (SELECT department_no FROM tb_department 
WHERE department_name = '음악학과')
GROUP BY STUDENT_NO, STUDENT_NAME;

-- 11

-- 뻑남(나중에 확인하기)
SELECT DEPARTMENT_NAME "하과"
FROM tb_student
JOIN tb_department USING (department_no)
JOIN tb_professor NO (COACH_PROFESSER_NO = PROFESSER_NO)
WHERE STUDENT_NO = 'A313047';

-- 12

--
SELECT *
FORM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE TERM_NO LIKE '2007%'
AND CLASS_NO
= (SELECT CLASS_NO FROM TB_CLASS WHERE CLASS_NAME = '인간관계론');

-- 13

-- 뻑남 오류가 없음
SELECT CLASS_NAME, department_NAME
FROM TB_CLASS T
LEFT JOIN  TB_CLASS_PROFESSOR CP USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IN NULL;

-- 14

--
SELECT STUDENT_NAME, NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT S
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE DEPARTMENT_NAME ='서반아어학과';

-- 15

--
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0;

-- 16

-- 뻑남
SELECT CLASS_NO, CLASS_NAME, AVG(POING)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE NEPARTMENT_NAME = '환경조경학과' AND
        CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17

-- 뻑남
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 
(SELECT DEPARTMENT_NO FROM TB_STUDENT
WHERE STUDENT_NAME = '최경희'); -- 이거 위험한 코드임 
-- 동명이인 이 있으면 오류남 그래서 =를 IN으로 바꾸거나 
-- STUDENT_NAME이거를 다른거로 바꾸거나 하셈
      
-- 18

--
--나중에 선생님 풀이에서 찾아서 보셈

-- 19

-- 뻑남
SELECT DEPARTMENT_NAME "계열 학과명", ROUNT(AVG(POING),1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE DEPARTMENT = 
(SELECT CATEGORY FROM TB_DEPARTMENT
        WHERE DEPARTMENT_NAME='환경조경학과')
AND CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME;









