-- 1
SELECT student_no as 학번, STUDENT_NAME as 이름, TO_CHAR(entrance_date, 'YYYY-MM-DD')
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY entrance_date; -- 기본값 오름차순 알지
--
SELECT student_no as 학번, STUDENT_NAME as 이름, ENTRANCE_DATE AS "입학연도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY 3;

--2
SELECT professor_NAME, professor_ssn
FROM tb_professor
WHERE NOT LENGTH(professor_NAME) = 3;
--WHERE professor_NAME NOT LIKE '___';

--3 -- 다시하기
SELECT professor_NAME, 
EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM 
TO_DATE(
CASE 
WHEN SUBSTR(professor_ssn,8,1) IN (1,2) THEN 19 || SUBSTR(professor_ssn,1,6)
WHEN SUBSTR(professor_ssn,8,1) IN (3,4) THEN 20 || SUBSTR(professor_ssn,1,6)
END)) AS "만나이"
FROM tb_professor
ORDER BY professor_ssn;

SELECT PROFESSOR_NAME AS 교수이름,
       FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD')) / 12) AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이 ASC;

--
SELECT PROFESSOR_NAME 교수이름,
EXTRACT(YEAR FROM SYSDATE) -
(19 || SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM TB_PROFESSOR
ORDER BY 2;

--4
SELECT SUBSTR(professor_NAME, 2, 2)
FROM tb_professor;
--
SELECT SUBSTR(professor_NAME,2) 이름
FROM tb_professor;

--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_NUMBER(TO_CHAR(ENTRANCE_DATE, 'YYYY')) - TO_NUMBER('19'||SUBSTR(STUDENT_SSN, 1, 2)) > 19;
--
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE (SUBSTR(STUDENT_SSN,1,2),'RR')) > 19;

--6
SELECT TO_CHAR(TO_DATE('201225'), 'MON DD DAY')
FROM DUAL;
--
SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY')
FROM DUAL;

--7
SELECT TO_CHAR(SYSDATE, 'RRRR') || '년' ||
TO_CHAR(SYSDATE, 'MON') || '월' ||
TO_CHAR(SYSDATE, 'DD') || '일 ' ||
TO_CHAR(SYSDATE, 'DAY') "현재 요일"
FROM DUAL;
---
-- 넘어감(사실 그냥 문제 보고 아느냐 하는 문제였음)

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE < TO_DATE('20000101', 'YYYYMMDD');
--
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9
SELECT ROUND(AVG(POINT), 1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT SUBSTR(TERM_NO,1,4)년도, ROUND((AVG(POINT), 1)) 학기,POINT 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);
--ORDER BY 1;

--13
SELECT DEPARTMENT_NO 학과코드명, COUNT(
    DECODE(ABSENCE_YN, 'Y', 1)
)
FROM TB_STUDENT 
--WHERE ABSENCE_YN = 'Y' -- 느려서 위에다가 한거
GROUP BY DEPARTMENT_NO;

--14
SELECT student_name, COUNT(*) AS 동명인수
FROM TB_STUDENT
GROUP BY student_name
HAVING COUNT(*) >= 2;

--15
SELECT SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2), ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE student_no = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY 1,2;









