-- 1
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);
--INSERT INTO TB_CATEGORY(NAME)
--VALUES('길똥');
--
--SELECT * FROM TB_CATEGORY;

-- 2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);
--INSERT INTO TB_CLASS_TYPE
--VALUES('1','길동');
--INSERT INTO TB_CLASS_TYPE
--VALUES('1','길똥');
--
--SELECT * FROM TB_CLASS_TYPE;

--3
ALTER TABLE TB_CATEGORY
ADD PRIMARY KEY(NAME);

--
--ALTER TABLE TB_CATEGORY
--ADD CONSTRAINT CATEGORY_NAME_PK PRIMARY KEY(NAME);
--                제약조건명         제약조건    (컬럼명)
INSERT INTO TB_CATEGORY(NAME)
VALUES('길똥');

--4
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL; -- NOT NULL은 왜MODIFY임? 이유없음 외우셈

INSERT INTO TB_CLASS_TYPE
VALUES('1',NULL);

--5
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

--6
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

SELECT * FROM TB_CATEGORY;
SELECT * FROM TB_CLASS_TYPE;

--7
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007196 TO PK_CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C007198 TO PK_CATEGORY_NAME;

--8
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;
SELECT * FROM TB_CATEGORY;

-- 9
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTNENT_CATEGORY 
FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY;

-- 10 -- VIEW 만드는거는 아직 안배움
-- 권한부여
--GRANT CREATE VIEW TO WORKBOOK;
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDETN_ADDRESS 주소
FROM tb_student;

-- 11
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME 학생이름, DEPARTMENT_NAME 학과이름, PROFESSOR_NAME 지도교수이름
FROM tb_student
JOIN tb_department USING(DEPARTMENT_NO)
LEFT JOIN tb_professor ON COACH_PROFESSOR_NO = PROFESSOR_NO
ORDER BY 2;
SELECT * FROM VW_지도면담;

-- 12 모든학과의 ...
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME , COUNT(*) STUDENT_COUNT
FROM tb_student
JOIN tb_department USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;

-- 13 -- 뻑남
UPDATE VW_학생일반정보
SET 학생이름 = '민경민'
WHERE 학번 = 'A213046';

-- 14
-- 이거는 선생님 풀이로 보기
-- 이거는 풀지말라고 한문제임
-- 안배워서


-- 15 2009~2005
SELECT * FROM(
SELECT CLASS_NO, CLASS_NAME, COUNT(*) "누적수강생수(명)" -- 누적수강생 수 
FROM tb_class
JOIN TB_GRADE USING(CLASS_NO)
WHERE 2009 - SUBSTR(TERM_NO, 1, 4) < 5
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 3 DESC)
WHERE ROWNUM <= 3;


-- 4번 실습문제 뭐시깽이 라고적으심


SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A213046';






